trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'mkdocs-builder'

steps:
- task: Docker@2
  displayName: 'Build MkDocs Docker Image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: '$(imageName)'

- task: Docker@2
  displayName: 'Run MkDocs Build Container'
  inputs:
    command: 'run'
    containerName: 'mkdocs-runner'
    imageName: '$(imageName)'
    options: '--rm -v $(Build.ArtifactStagingDirectory):/output'
    arguments: '/bin/sh -c "mkdocs build -d /output"'

- task: PublishBuildArtifacts@1
  displayName: 'Publish MkDocs Site'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'mkdocs-site'
