version: '3.8'

services:
  plantuml:
    image: plantuml/plantuml-server:latest
    container_name: plantuml-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    profiles: ["local"]

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkdocs-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PLANTUML_HOST=${PLANTUML_HOST}
    command: mkdocs serve --dev-addr=0.0.0.0:8000 --livereload
