site_name: My Azure-deployed Demo Project for OPS

nav:
    - Home: index.md
    - About: about.md
    - Demo Glossary for the 2025 gig:
        - Cloud & DevOps Glossary: cloud_devops_glossary.md
    - Other Glossaries and Terms:
        - OSS Terms: gloss_oss.md
        - Kubernetes Terms: gloss_kuber.md
        - Cloud Native Terms: gloss_cloud-native.md
    - Misc Cheat Sheets:
        - kubectl cheatsheet: cheatsheet-kubectl.md
        - Miscellaneous cheatsheets: cheatsheets.md
theme: material
extra:
    generator: true