site_name: "Ler's Demo Website"
site_url: https://cassmastern.github.io/demo4ops/
docs_dir: docs

theme:
  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico
  features:
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - About this Site:
      - "What's in Here?": whatsinhere.md
      - How this Site was Developed and Deployed: about.md
      - Feedback: feedback.md
      - Rough Roadmap and Changelog: roadmap.md
  - Probably What Awaits Me at Work:
      - AWS vs GCP vs Azure: aws-gcp-azure.md
      - Cross-Platform Cloud and DevOps Glossary: aws-gcp-azure_glossary.md
      - A Jakarta EE App on Azure: jakarta-ee-azure.md
  - Networking and Security in 2025:
      - A Hypothetical Data Centre Network: network_data_center.md
      - Threat Modelling - STRIDE: network_data_center_stride.md
      - "Threat Modeling - MITRE ATT&CK": network_data_center_mitre.md
  - Some Other Glossaries:
      - Glossary of OSS Terms: gloss_oss.md
      - Glossary of Networking Terms: gloss_networking.md
      - Glossary of Kubernetes Terms: gloss_kuber.md
      - Glossary of Cloud-Native Terms: gloss_cloud-native.md
  - Cheat Sheets:
      - Docker Command Cheat Sheet: cheatsheet-docker.md
      - Kubectl Command Cheat Sheet: cheatsheet-kubectl.md
      - Compound Modifiers Cheat Sheet: cheatsheet_compound-modifiers.md
  - Bonus (Bloggish):
      - 'IBM-SanFrancisco — a Technical Memoir': ibm-sanfran.md
      - Visuals for the Sightless: visuals-for-the-sightless.md
      - AI-Augmented Accessibility — a Technical Daydream: ai-accessibility.md
      - From Daydream to Concept Note: ai-accessibility_bus.md
      
extra:
  generator: false
  analytics:
    provider: google
    property: G-GD2XWDMP2E
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - toc:
      permalink: true

extra_javascript:
  - js/diagram-zoom.js
  - js/alphabet-auto.js
  - js/alttext-inject.js
    
extra_css:
  - css/alphabet.css
  - css/diagram-zoom.css
  - css/cm-logo.css