site_name: My Azure-deployed Demo Project for OPS
nav:
    - Home: index.md
    - About: about.md
    - OSS Terms: gloss_oss.md
    - Kubernetes Terms: gloss_kuber.md
    - Cloud Native Terms: gloss_cloud-native.md
    - kubectl cheatsheet: cheatsheet-kubectl.md
    - Miscellaneous cheatsheets: cheatsheets.md
theme: material
extra:
    generator: true