site_name: My MKdocs project
nav:
    - Home: index.md
    - About: about.md
    - Glossary: Gloss.md
    - OSS Terms: gloss_oss.md
    - Kubernetes Terms: gloss_kuber.md
    - Cloud Native Terms: gloss_cloud-native.md
    - Miscellaneous cheatsheets: cheatsheets.md
theme: readthedocs
extra:
    generator: false