site_name: My Azure-deployed Demo Project for OPS
theme: material
plugins:
  - search
  - mermaid2
nav:
    - Home: index.md
    - About this Site: about.md
    - Demo Content for OPS 2025:
        - Cloud & DevOps Glossary: cloud_devops_glossary.md
    - Other Glossaries and Terms [legacy]:
        - OSS Terms: gloss_oss.md
        - Kubernetes Terms: gloss_kuber.md
        - Cloud Native Terms: gloss_cloud-native.md
    - Misc Cheat Sheets [legacy]:
        - kubectl cheatsheet: cheatsheet-kubectl.md
        - Miscellaneous cheatsheets: cheatsheets.md
extra:
    generator: true

extra_javascript:
  - js/alphabet-auto.js

extra_css:
  - css/alphabet.css
