site_name: "Ler's Azure-deployed Demo Site"
theme: material
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - AWS vs GCP vs Azure: aws-gcp-azure.md
  - Cloud & DevOps Glossary (AWS, GCP, Azure): gloss_cloud_devops_AWS-GCP-Azure.md
  - A Jakarta EE App on Azure: jakarta-ee-azure.md
  - Some Glossaries:
      - OSS Terms: gloss_oss.md
      - Kubernetes Terms: gloss_kuber.md
      - Cloud Native Terms: gloss_cloud-native.md
  - Miscellaneous Cheat Sheets:
      - kubectl cheatsheet: cheatsheet-kubectl.md
      - Miscellaneous cheatsheets: cheatsheets.md
extra:
    generator: true

extra_javascript:
  - js/alphabet-auto.js
  - js/diagram-zoom.js

extra_css:
  - css/alphabet.css
  - css/diagram-zoom.css

