site_name: "Ler's Demo Website"
site_url: https://cassmastern.github.io/demo4ops/
docs_dir: docs
copyright: "<a href='https://cassmastern.github.io/demo4ops/feedback/'><span class='logo-text'>CM</span> 2025.</a>"

theme:
  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

plugins:
  - search
  - mermaid2:
      javascript: js/mermaid.min.js
  - awesome-pages

extra:
  generator: false
  analytics:
    provider: google
    property: G-GD2XWDMP2E
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - toc:
      permalink: true

extra_javascript:
  - js/seamaiden-theme-switchr.js
  - js/diagram-zoom.js
  - js/alphabet-auto.js
#  - js/alttext-inject.js

    
extra_css:
  - css/alphabet.css
  - css/diagram-zoom.css
  - css/cm-logo.css
  - css/color-vars.css
  