site_name: My MKdocs project for Hansencx
nav:
    - Home: index.md
    - About: about.md
    - OSS Terms: gloss_oss.md
    - Kubernetes Terms: gloss_kuber.md
    - Cloud Native Terms: gloss_cloud-native.md
    - kubectl cheatsheet: cheatsheet-kubectl.md
    - Miscellaneous cheatsheets: cheatsheets.md
theme: material
highlightjs: true
hljs_languages:
    - yaml
    - rust
extra_css:
    - extra.css
extra:
    generator: false 