name: Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🏗️ Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: mkdocs-builder:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: ✅ Verify mermaid.min.js presence
        run: |
          if [ ! -f "docs/js/mermaid.min.js" ]; then
            echo "ERROR: Mermaid JS asset missing at docs/js/mermaid.min.js"
            exit 1
          fi
          echo "Found mermaid.min.js"
          sha256sum docs/js/mermaid.min.js

      - name: Build MkDocs site
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            mkdocs-builder:latest \
            mkdocs build --verbose

      - name: 🔍 Verify build output
        run: |
          if [ ! -d "./site" ]; then
            echo "ERROR: MkDocs output folder './site' not found."
            ls -la ./
            exit 1
          fi
          echo "Build output directory found"

          essential_files=(
            "index.html"
            "search/search_index.json"
            "js/alttext-inject.js"
            "js/diagram-zoom.js"
            "css/accessibility.css"
            "css/diagram-zoom.css"
            "js/mermaid.min.js"
          )

          for file in "${essential_files[@]}"; do
            if [ -f "./site/$file" ]; then
              echo "Found: $file"
            else
              echo "Missing: $file"
            fi
          done

          mermaid_count=$(find ./site -name "*.html" -exec grep -l "mermaid" {} \; | wc -l)
          echo "Found $mermaid_count HTML files with Mermaid content"

          if [ -f "./site/js/alttext-inject.js" ]; then
            js_size=$(stat -c%s "./site/js/alttext-inject.js")
            echo "alttext-inject.js size: ${js_size} bytes"
          fi
